
//input ports
add mapped point clk clk -type PI PI
add mapped point reset_l reset_l -type PI PI
add mapped point porborn porborn -type PI PI
add mapped point SPI_CS SPI_CS -type PI PI
add mapped point SPI_Clk SPI_Clk -type PI PI
add mapped point SPI_MOSI SPI_MOSI -type PI PI
add mapped point IC_addr[1] IC_addr[1] -type PI PI
add mapped point IC_addr[0] IC_addr[0] -type PI PI

//output ports
add mapped point up_switches[31] up_switches[31] -type PO PO
add mapped point up_switches[30] up_switches[30] -type PO PO
add mapped point up_switches[29] up_switches[29] -type PO PO
add mapped point up_switches[28] up_switches[28] -type PO PO
add mapped point up_switches[27] up_switches[27] -type PO PO
add mapped point up_switches[26] up_switches[26] -type PO PO
add mapped point up_switches[25] up_switches[25] -type PO PO
add mapped point up_switches[24] up_switches[24] -type PO PO
add mapped point up_switches[23] up_switches[23] -type PO PO
add mapped point up_switches[22] up_switches[22] -type PO PO
add mapped point up_switches[21] up_switches[21] -type PO PO
add mapped point up_switches[20] up_switches[20] -type PO PO
add mapped point up_switches[19] up_switches[19] -type PO PO
add mapped point up_switches[18] up_switches[18] -type PO PO
add mapped point up_switches[17] up_switches[17] -type PO PO
add mapped point up_switches[16] up_switches[16] -type PO PO
add mapped point up_switches[15] up_switches[15] -type PO PO
add mapped point up_switches[14] up_switches[14] -type PO PO
add mapped point up_switches[13] up_switches[13] -type PO PO
add mapped point up_switches[12] up_switches[12] -type PO PO
add mapped point up_switches[11] up_switches[11] -type PO PO
add mapped point up_switches[10] up_switches[10] -type PO PO
add mapped point up_switches[9] up_switches[9] -type PO PO
add mapped point up_switches[8] up_switches[8] -type PO PO
add mapped point up_switches[7] up_switches[7] -type PO PO
add mapped point up_switches[6] up_switches[6] -type PO PO
add mapped point up_switches[5] up_switches[5] -type PO PO
add mapped point up_switches[4] up_switches[4] -type PO PO
add mapped point up_switches[3] up_switches[3] -type PO PO
add mapped point up_switches[2] up_switches[2] -type PO PO
add mapped point up_switches[1] up_switches[1] -type PO PO
add mapped point up_switches[0] up_switches[0] -type PO PO
add mapped point down_switches[31] down_switches[31] -type PO PO
add mapped point down_switches[30] down_switches[30] -type PO PO
add mapped point down_switches[29] down_switches[29] -type PO PO
add mapped point down_switches[28] down_switches[28] -type PO PO
add mapped point down_switches[27] down_switches[27] -type PO PO
add mapped point down_switches[26] down_switches[26] -type PO PO
add mapped point down_switches[25] down_switches[25] -type PO PO
add mapped point down_switches[24] down_switches[24] -type PO PO
add mapped point down_switches[23] down_switches[23] -type PO PO
add mapped point down_switches[22] down_switches[22] -type PO PO
add mapped point down_switches[21] down_switches[21] -type PO PO
add mapped point down_switches[20] down_switches[20] -type PO PO
add mapped point down_switches[19] down_switches[19] -type PO PO
add mapped point down_switches[18] down_switches[18] -type PO PO
add mapped point down_switches[17] down_switches[17] -type PO PO
add mapped point down_switches[16] down_switches[16] -type PO PO
add mapped point down_switches[15] down_switches[15] -type PO PO
add mapped point down_switches[14] down_switches[14] -type PO PO
add mapped point down_switches[13] down_switches[13] -type PO PO
add mapped point down_switches[12] down_switches[12] -type PO PO
add mapped point down_switches[11] down_switches[11] -type PO PO
add mapped point down_switches[10] down_switches[10] -type PO PO
add mapped point down_switches[9] down_switches[9] -type PO PO
add mapped point down_switches[8] down_switches[8] -type PO PO
add mapped point down_switches[7] down_switches[7] -type PO PO
add mapped point down_switches[6] down_switches[6] -type PO PO
add mapped point down_switches[5] down_switches[5] -type PO PO
add mapped point down_switches[4] down_switches[4] -type PO PO
add mapped point down_switches[3] down_switches[3] -type PO PO
add mapped point down_switches[2] down_switches[2] -type PO PO
add mapped point down_switches[1] down_switches[1] -type PO PO
add mapped point down_switches[0] down_switches[0] -type PO PO
add mapped point DAC[5] DAC[5] -type PO PO
add mapped point DAC[4] DAC[4] -type PO PO
add mapped point DAC[3] DAC[3] -type PO PO
add mapped point DAC[2] DAC[2] -type PO PO
add mapped point DAC[1] DAC[1] -type PO PO
add mapped point DAC[0] DAC[0] -type PO PO
add mapped point pulse_active pulse_active -type PO PO
add mapped point enable enable -type PO PO

//inout ports




//Sequential Pins
add mapped point npg1/pulse_start/q npg1_pulse_start_reg/Q -type DFF DFF
add mapped point npg1/DAC_cont[0]/q npg1_DAC_cont_reg[0]/Q -type DFF DFF
add mapped point npg1/DAC_cont[1]/q npg1_DAC_cont_reg[1]/Q -type DFF DFF
add mapped point npg1/DAC_cont[2]/q npg1_DAC_cont_reg[2]/Q -type DFF DFF
add mapped point npg1/DAC_cont[3]/q npg1_DAC_cont_reg[3]/Q -type DFF DFF
add mapped point npg1/DAC_cont[4]/q npg1_DAC_cont_reg[4]/Q -type DFF DFF
add mapped point npg1/DAC_cont[5]/q npg1_DAC_cont_reg[5]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[0]/q npg1_DOWN_accumulator_reg[0]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[1]/q npg1_DOWN_accumulator_reg[1]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[2]/q npg1_DOWN_accumulator_reg[2]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[3]/q npg1_DOWN_accumulator_reg[3]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[4]/q npg1_DOWN_accumulator_reg[4]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[5]/q npg1_DOWN_accumulator_reg[5]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[6]/q npg1_DOWN_accumulator_reg[6]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[7]/q npg1_DOWN_accumulator_reg[7]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[8]/q npg1_DOWN_accumulator_reg[8]/Q -type DFF DFF
add mapped point npg1/DOWN_accumulator[9]/q npg1_DOWN_accumulator_reg[9]/Q -type DFF DFF
add mapped point npg1/DOWN_count[0]/q npg1_DOWN_count_reg[0]/Q -type DFF DFF
add mapped point npg1/DOWN_count[1]/q npg1_DOWN_count_reg[1]/Q -type DFF DFF
add mapped point npg1/DOWN_count[2]/q npg1_DOWN_count_reg[2]/Q -type DFF DFF
add mapped point npg1/DOWN_count[3]/q npg1_DOWN_count_reg[3]/Q -type DFF DFF
add mapped point npg1/DOWN_count[4]/q npg1_DOWN_count_reg[4]/Q -type DFF DFF
add mapped point npg1/DOWN_count[5]/q npg1_DOWN_count_reg[5]/Q -type DFF DFF
add mapped point npg1/OFF_count[0]/q npg1_OFF_count_reg[0]/Q -type DFF DFF
add mapped point npg1/OFF_count[1]/q npg1_OFF_count_reg[1]/Q -type DFF DFF
add mapped point npg1/OFF_count[2]/q npg1_OFF_count_reg[2]/Q -type DFF DFF
add mapped point npg1/OFF_count[3]/q npg1_OFF_count_reg[3]/Q -type DFF DFF
add mapped point npg1/OFF_count[4]/q npg1_OFF_count_reg[4]/Q -type DFF DFF
add mapped point npg1/OFF_count[5]/q npg1_OFF_count_reg[5]/Q -type DFF DFF
add mapped point npg1/OFF_count[6]/q npg1_OFF_count_reg[6]/Q -type DFF DFF
add mapped point npg1/OFF_count[7]/q npg1_OFF_count_reg[7]/Q -type DFF DFF
add mapped point npg1/OFF_count[8]/q npg1_OFF_count_reg[8]/Q -type DFF DFF
add mapped point npg1/OFF_count[9]/q npg1_OFF_count_reg[9]/Q -type DFF DFF
add mapped point npg1/ON_count[0]/q npg1_ON_count_reg[0]/Q -type DFF DFF
add mapped point npg1/ON_count[1]/q npg1_ON_count_reg[1]/Q -type DFF DFF
add mapped point npg1/ON_count[2]/q npg1_ON_count_reg[2]/Q -type DFF DFF
add mapped point npg1/ON_count[3]/q npg1_ON_count_reg[3]/Q -type DFF DFF
add mapped point npg1/ON_count[4]/q npg1_ON_count_reg[4]/Q -type DFF DFF
add mapped point npg1/ON_count[5]/q npg1_ON_count_reg[5]/Q -type DFF DFF
add mapped point npg1/ON_count[6]/q npg1_ON_count_reg[6]/Q -type DFF DFF
add mapped point npg1/ON_count[7]/q npg1_ON_count_reg[7]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[0]/q npg1_UP_accumulator_reg[0]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[1]/q npg1_UP_accumulator_reg[1]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[2]/q npg1_UP_accumulator_reg[2]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[3]/q npg1_UP_accumulator_reg[3]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[4]/q npg1_UP_accumulator_reg[4]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[5]/q npg1_UP_accumulator_reg[5]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[6]/q npg1_UP_accumulator_reg[6]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[7]/q npg1_UP_accumulator_reg[7]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[8]/q npg1_UP_accumulator_reg[8]/Q -type DFF DFF
add mapped point npg1/UP_accumulator[9]/q npg1_UP_accumulator_reg[9]/Q -type DFF DFF
add mapped point npg1/UP_count[0]/q npg1_UP_count_reg[0]/Q -type DFF DFF
add mapped point npg1/UP_count[1]/q npg1_UP_count_reg[1]/Q -type DFF DFF
add mapped point npg1/UP_count[2]/q npg1_UP_count_reg[2]/Q -type DFF DFF
add mapped point npg1/UP_count[3]/q npg1_UP_count_reg[3]/Q -type DFF DFF
add mapped point npg1/UP_count[4]/q npg1_UP_count_reg[4]/Q -type DFF DFF
add mapped point npg1/UP_count[5]/q npg1_UP_count_reg[5]/Q -type DFF DFF
add mapped point npg1/freq_count[0]/q npg1_freq_count_reg[0]/Q -type DFF DFF
add mapped point npg1/freq_count[1]/q npg1_freq_count_reg[1]/Q -type DFF DFF
add mapped point npg1/freq_count[2]/q npg1_freq_count_reg[2]/Q -type DFF DFF
add mapped point npg1/freq_count[3]/q npg1_freq_count_reg[3]/Q -type DFF DFF
add mapped point npg1/freq_count[4]/q npg1_freq_count_reg[4]/Q -type DFF DFF
add mapped point npg1/freq_count[5]/q npg1_freq_count_reg[5]/Q -type DFF DFF
add mapped point npg1/freq_count[6]/q npg1_freq_count_reg[6]/Q -type DFF DFF
add mapped point npg1/freq_count[7]/q npg1_freq_count_reg[7]/Q -type DFF DFF
add mapped point npg1/freq_count[8]/q npg1_freq_count_reg[8]/Q -type DFF DFF
add mapped point npg1/freq_count[9]/q npg1_freq_count_reg[9]/Q -type DFF DFF
add mapped point npg1/freq_count[10]/q npg1_freq_count_reg[10]/Q -type DFF DFF
add mapped point npg1/freq_count[11]/q npg1_freq_count_reg[11]/Q -type DFF DFF
add mapped point npg1/on_off_ctrl[0]/q npg1_on_off_ctrl_reg[0]/Q -type DFF DFF
add mapped point npg1/on_off_ctrl[1]/q npg1_on_off_ctrl_reg[1]/Q -type DFF DFF
add mapped point npg1/on_off_ctrl[2]/q npg1_on_off_ctrl_reg[2]/Q -type DFF DFF
add mapped point npg1/phase_down_count[0]/q npg1_phase_down_count_reg[0]/Q -type DFF DFF
add mapped point npg1/phase_down_count[1]/q npg1_phase_down_count_reg[1]/Q -type DFF DFF
add mapped point npg1/phase_down_count[2]/q npg1_phase_down_count_reg[2]/Q -type DFF DFF
add mapped point npg1/phase_down_state/q npg1_phase_down_state_reg/Q -type DFF DFF
add mapped point npg1/phase_pause_ready/q npg1_phase_pause_ready_reg/Q -type DFF DFF
add mapped point npg1/phase_up_count[0]/q npg1_phase_up_count_reg[0]/Q -type DFF DFF
add mapped point npg1/phase_up_count[1]/q npg1_phase_up_count_reg[1]/Q -type DFF DFF
add mapped point npg1/phase_up_count[2]/q npg1_phase_up_count_reg[2]/Q -type DFF DFF
add mapped point npg1/phase_up_state/q npg1_phase_up_state_reg/Q -type DFF DFF
add mapped point npg1/pulse_aux/q npg1_pulse_aux_reg/Q -type DFF DFF
add mapped point spi1/conf0_meta[0]/q spi1_conf0_meta_reg[0]/Q -type DFF DFF
add mapped point spi1/conf0_meta[1]/q spi1_conf0_meta_reg[1]/Q -type DFF DFF
add mapped point spi1/conf0_meta[2]/q spi1_conf0_meta_reg[2]/Q -type DFF DFF
add mapped point spi1/conf0_meta[3]/q spi1_conf0_meta_reg[3]/Q -type DFF DFF
add mapped point spi1/conf0_meta[4]/q spi1_conf0_meta_reg[4]/Q -type DFF DFF
add mapped point spi1/conf0_meta[5]/q spi1_conf0_meta_reg[5]/Q -type DFF DFF
add mapped point spi1/conf0_meta[6]/q spi1_conf0_meta_reg[6]/Q -type DFF DFF
add mapped point spi1/conf0_meta[7]/q spi1_conf0_meta_reg[7]/Q -type DFF DFF
add mapped point spi1/conf0_meta[8]/q spi1_conf0_meta_reg[8]/Q -type DFF DFF
add mapped point spi1/conf0_meta[9]/q spi1_conf0_meta_reg[9]/Q -type DFF DFF
add mapped point spi1/conf0_meta[10]/q spi1_conf0_meta_reg[10]/Q -type DFF DFF
add mapped point spi1/conf0_meta[11]/q spi1_conf0_meta_reg[11]/Q -type DFF DFF
add mapped point spi1/conf0_meta[12]/q spi1_conf0_meta_reg[12]/Q -type DFF DFF
add mapped point spi1/conf0_meta[13]/q spi1_conf0_meta_reg[13]/Q -type DFF DFF
add mapped point spi1/conf0_meta[14]/q spi1_conf0_meta_reg[14]/Q -type DFF DFF
add mapped point spi1/conf0_meta[15]/q spi1_conf0_meta_reg[15]/Q -type DFF DFF
add mapped point spi1/conf0_meta[16]/q spi1_conf0_meta_reg[16]/Q -type DFF DFF
add mapped point spi1/conf0_meta[17]/q spi1_conf0_meta_reg[17]/Q -type DFF DFF
add mapped point spi1/conf0_meta[18]/q spi1_conf0_meta_reg[18]/Q -type DFF DFF
add mapped point spi1/conf0_meta[19]/q spi1_conf0_meta_reg[19]/Q -type DFF DFF
add mapped point spi1/conf0_meta[20]/q spi1_conf0_meta_reg[20]/Q -type DFF DFF
add mapped point spi1/conf0_meta[21]/q spi1_conf0_meta_reg[21]/Q -type DFF DFF
add mapped point spi1/conf0_meta[22]/q spi1_conf0_meta_reg[22]/Q -type DFF DFF
add mapped point spi1/conf0_meta[23]/q spi1_conf0_meta_reg[23]/Q -type DFF DFF
add mapped point spi1/conf0_meta[24]/q spi1_conf0_meta_reg[24]/Q -type DFF DFF
add mapped point spi1/conf0_meta[25]/q spi1_conf0_meta_reg[25]/Q -type DFF DFF
add mapped point spi1/conf0_meta[26]/q spi1_conf0_meta_reg[26]/Q -type DFF DFF
add mapped point spi1/conf0_meta[27]/q spi1_conf0_meta_reg[27]/Q -type DFF DFF
add mapped point spi1/conf0_meta[28]/q spi1_conf0_meta_reg[28]/Q -type DFF DFF
add mapped point spi1/conf0_meta[29]/q spi1_conf0_meta_reg[29]/Q -type DFF DFF
add mapped point spi1/conf0_meta[30]/q spi1_conf0_meta_reg[30]/Q -type DFF DFF
add mapped point spi1/conf0_meta[31]/q spi1_conf0_meta_reg[31]/Q -type DFF DFF
add mapped point spi1/conf0[0]/q spi1_conf0_reg[0]/Q -type DFF DFF
add mapped point spi1/conf0[1]/q spi1_conf0_reg[1]/Q -type DFF DFF
add mapped point spi1/conf0[2]/q spi1_conf0_reg[2]/Q -type DFF DFF
add mapped point spi1/conf0[3]/q spi1_conf0_reg[3]/Q -type DFF DFF
add mapped point spi1/conf0[4]/q spi1_conf0_reg[4]/Q -type DFF DFF
add mapped point spi1/conf0[5]/q spi1_conf0_reg[5]/Q -type DFF DFF
add mapped point spi1/conf0[6]/q spi1_conf0_reg[6]/Q -type DFF DFF
add mapped point spi1/conf0[7]/q spi1_conf0_reg[7]/Q -type DFF DFF
add mapped point spi1/conf0[8]/q spi1_conf0_reg[8]/Q -type DFF DFF
add mapped point spi1/conf0[9]/q spi1_conf0_reg[9]/Q -type DFF DFF
add mapped point spi1/conf0[10]/q spi1_conf0_reg[10]/Q -type DFF DFF
add mapped point spi1/conf0[11]/q spi1_conf0_reg[11]/Q -type DFF DFF
add mapped point spi1/conf0[12]/q spi1_conf0_reg[12]/Q -type DFF DFF
add mapped point spi1/conf0[13]/q spi1_conf0_reg[13]/Q -type DFF DFF
add mapped point spi1/conf0[14]/q spi1_conf0_reg[14]/Q -type DFF DFF
add mapped point spi1/conf0[15]/q spi1_conf0_reg[15]/Q -type DFF DFF
add mapped point spi1/conf0[16]/q spi1_conf0_reg[16]/Q -type DFF DFF
add mapped point spi1/conf0[17]/q spi1_conf0_reg[17]/Q -type DFF DFF
add mapped point spi1/conf0[18]/q spi1_conf0_reg[18]/Q -type DFF DFF
add mapped point spi1/conf0[19]/q spi1_conf0_reg[19]/Q -type DFF DFF
add mapped point spi1/conf0[20]/q spi1_conf0_reg[20]/Q -type DFF DFF
add mapped point spi1/conf0[21]/q spi1_conf0_reg[21]/Q -type DFF DFF
add mapped point spi1/conf0[22]/q spi1_conf0_reg[22]/Q -type DFF DFF
add mapped point spi1/conf0[23]/q spi1_conf0_reg[23]/Q -type DFF DFF
add mapped point spi1/conf0[24]/q spi1_conf0_reg[24]/Q -type DFF DFF
add mapped point spi1/conf0[25]/q spi1_conf0_reg[25]/Q -type DFF DFF
add mapped point spi1/conf0[26]/q spi1_conf0_reg[26]/Q -type DFF DFF
add mapped point spi1/conf0[27]/q spi1_conf0_reg[27]/Q -type DFF DFF
add mapped point spi1/conf0[28]/q spi1_conf0_reg[28]/Q -type DFF DFF
add mapped point spi1/conf0[29]/q spi1_conf0_reg[29]/Q -type DFF DFF
add mapped point spi1/conf0[30]/q spi1_conf0_reg[30]/Q -type DFF DFF
add mapped point spi1/conf0[31]/q spi1_conf0_reg[31]/Q -type DFF DFF
add mapped point spi1/conf1_meta[0]/q spi1_conf1_meta_reg[0]/Q -type DFF DFF
add mapped point spi1/conf1_meta[1]/q spi1_conf1_meta_reg[1]/Q -type DFF DFF
add mapped point spi1/conf1_meta[2]/q spi1_conf1_meta_reg[2]/Q -type DFF DFF
add mapped point spi1/conf1_meta[3]/q spi1_conf1_meta_reg[3]/Q -type DFF DFF
add mapped point spi1/conf1_meta[4]/q spi1_conf1_meta_reg[4]/Q -type DFF DFF
add mapped point spi1/conf1_meta[5]/q spi1_conf1_meta_reg[5]/Q -type DFF DFF
add mapped point spi1/conf1_meta[6]/q spi1_conf1_meta_reg[6]/Q -type DFF DFF
add mapped point spi1/conf1_meta[7]/q spi1_conf1_meta_reg[7]/Q -type DFF DFF
add mapped point spi1/conf1_meta[8]/q spi1_conf1_meta_reg[8]/Q -type DFF DFF
add mapped point spi1/conf1_meta[9]/q spi1_conf1_meta_reg[9]/Q -type DFF DFF
add mapped point spi1/conf1_meta[10]/q spi1_conf1_meta_reg[10]/Q -type DFF DFF
add mapped point spi1/conf1_meta[11]/q spi1_conf1_meta_reg[11]/Q -type DFF DFF
add mapped point spi1/conf1_meta[12]/q spi1_conf1_meta_reg[12]/Q -type DFF DFF
add mapped point spi1/conf1_meta[13]/q spi1_conf1_meta_reg[13]/Q -type DFF DFF
add mapped point spi1/conf1_meta[14]/q spi1_conf1_meta_reg[14]/Q -type DFF DFF
add mapped point spi1/conf1_meta[15]/q spi1_conf1_meta_reg[15]/Q -type DFF DFF
add mapped point spi1/conf1_meta[16]/q spi1_conf1_meta_reg[16]/Q -type DFF DFF
add mapped point spi1/conf1_meta[17]/q spi1_conf1_meta_reg[17]/Q -type DFF DFF
add mapped point spi1/conf1_meta[18]/q spi1_conf1_meta_reg[18]/Q -type DFF DFF
add mapped point spi1/conf1_meta[19]/q spi1_conf1_meta_reg[19]/Q -type DFF DFF
add mapped point spi1/conf1_meta[20]/q spi1_conf1_meta_reg[20]/Q -type DFF DFF
add mapped point spi1/conf1_meta[21]/q spi1_conf1_meta_reg[21]/Q -type DFF DFF
add mapped point spi1/conf1_meta[22]/q spi1_conf1_meta_reg[22]/Q -type DFF DFF
add mapped point spi1/conf1_meta[23]/q spi1_conf1_meta_reg[23]/Q -type DFF DFF
add mapped point spi1/conf1[0]/q spi1_conf1_reg[0]/Q -type DFF DFF
add mapped point spi1/conf1[1]/q spi1_conf1_reg[1]/Q -type DFF DFF
add mapped point spi1/conf1[2]/q spi1_conf1_reg[2]/Q -type DFF DFF
add mapped point spi1/conf1[3]/q spi1_conf1_reg[3]/Q -type DFF DFF
add mapped point spi1/conf1[4]/q spi1_conf1_reg[4]/Q -type DFF DFF
add mapped point spi1/conf1[5]/q spi1_conf1_reg[5]/Q -type DFF DFF
add mapped point spi1/conf1[6]/q spi1_conf1_reg[6]/Q -type DFF DFF
add mapped point spi1/conf1[7]/q spi1_conf1_reg[7]/Q -type DFF DFF
add mapped point spi1/conf1[8]/q spi1_conf1_reg[8]/Q -type DFF DFF
add mapped point spi1/conf1[9]/q spi1_conf1_reg[9]/Q -type DFF DFF
add mapped point spi1/conf1[10]/q spi1_conf1_reg[10]/Q -type DFF DFF
add mapped point spi1/conf1[11]/q spi1_conf1_reg[11]/Q -type DFF DFF
add mapped point spi1/conf1[12]/q spi1_conf1_reg[12]/Q -type DFF DFF
add mapped point spi1/conf1[13]/q spi1_conf1_reg[13]/Q -type DFF DFF
add mapped point spi1/conf1[14]/q spi1_conf1_reg[14]/Q -type DFF DFF
add mapped point spi1/conf1[15]/q spi1_conf1_reg[15]/Q -type DFF DFF
add mapped point spi1/conf1[16]/q spi1_conf1_reg[16]/Q -type DFF DFF
add mapped point spi1/conf1[17]/q spi1_conf1_reg[17]/Q -type DFF DFF
add mapped point spi1/conf1[18]/q spi1_conf1_reg[18]/Q -type DFF DFF
add mapped point spi1/conf1[19]/q spi1_conf1_reg[19]/Q -type DFF DFF
add mapped point spi1/conf1[20]/q spi1_conf1_reg[20]/Q -type DFF DFF
add mapped point spi1/conf1[21]/q spi1_conf1_reg[21]/Q -type DFF DFF
add mapped point spi1/conf1[22]/q spi1_conf1_reg[22]/Q -type DFF DFF
add mapped point spi1/conf1[23]/q spi1_conf1_reg[23]/Q -type DFF DFF
add mapped point spi1/ele1_meta[0]/q spi1_ele1_meta_reg[0]/Q -type DFF DFF
add mapped point spi1/ele1_meta[1]/q spi1_ele1_meta_reg[1]/Q -type DFF DFF
add mapped point spi1/ele1_meta[2]/q spi1_ele1_meta_reg[2]/Q -type DFF DFF
add mapped point spi1/ele1_meta[3]/q spi1_ele1_meta_reg[3]/Q -type DFF DFF
add mapped point spi1/ele1_meta[4]/q spi1_ele1_meta_reg[4]/Q -type DFF DFF
add mapped point spi1/ele1_meta[5]/q spi1_ele1_meta_reg[5]/Q -type DFF DFF
add mapped point spi1/ele1_meta[6]/q spi1_ele1_meta_reg[6]/Q -type DFF DFF
add mapped point spi1/ele1_meta[7]/q spi1_ele1_meta_reg[7]/Q -type DFF DFF
add mapped point spi1/ele1_meta[8]/q spi1_ele1_meta_reg[8]/Q -type DFF DFF
add mapped point spi1/ele1_meta[9]/q spi1_ele1_meta_reg[9]/Q -type DFF DFF
add mapped point spi1/ele1_meta[10]/q spi1_ele1_meta_reg[10]/Q -type DFF DFF
add mapped point spi1/ele1_meta[11]/q spi1_ele1_meta_reg[11]/Q -type DFF DFF
add mapped point spi1/ele1_meta[12]/q spi1_ele1_meta_reg[12]/Q -type DFF DFF
add mapped point spi1/ele1_meta[13]/q spi1_ele1_meta_reg[13]/Q -type DFF DFF
add mapped point spi1/ele1_meta[14]/q spi1_ele1_meta_reg[14]/Q -type DFF DFF
add mapped point spi1/ele1_meta[15]/q spi1_ele1_meta_reg[15]/Q -type DFF DFF
add mapped point spi1/ele1_meta[16]/q spi1_ele1_meta_reg[16]/Q -type DFF DFF
add mapped point spi1/ele1_meta[17]/q spi1_ele1_meta_reg[17]/Q -type DFF DFF
add mapped point spi1/ele1_meta[18]/q spi1_ele1_meta_reg[18]/Q -type DFF DFF
add mapped point spi1/ele1_meta[19]/q spi1_ele1_meta_reg[19]/Q -type DFF DFF
add mapped point spi1/ele1_meta[20]/q spi1_ele1_meta_reg[20]/Q -type DFF DFF
add mapped point spi1/ele1_meta[21]/q spi1_ele1_meta_reg[21]/Q -type DFF DFF
add mapped point spi1/ele1_meta[22]/q spi1_ele1_meta_reg[22]/Q -type DFF DFF
add mapped point spi1/ele1_meta[23]/q spi1_ele1_meta_reg[23]/Q -type DFF DFF
add mapped point spi1/ele1_meta[24]/q spi1_ele1_meta_reg[24]/Q -type DFF DFF
add mapped point spi1/ele1_meta[25]/q spi1_ele1_meta_reg[25]/Q -type DFF DFF
add mapped point spi1/ele1_meta[26]/q spi1_ele1_meta_reg[26]/Q -type DFF DFF
add mapped point spi1/ele1_meta[27]/q spi1_ele1_meta_reg[27]/Q -type DFF DFF
add mapped point spi1/ele1_meta[28]/q spi1_ele1_meta_reg[28]/Q -type DFF DFF
add mapped point spi1/ele1_meta[29]/q spi1_ele1_meta_reg[29]/Q -type DFF DFF
add mapped point spi1/ele1_meta[30]/q spi1_ele1_meta_reg[30]/Q -type DFF DFF
add mapped point spi1/ele1_meta[31]/q spi1_ele1_meta_reg[31]/Q -type DFF DFF
add mapped point spi1/ele1[0]/q spi1_ele1_reg[0]/Q -type DFF DFF
add mapped point spi1/ele1[1]/q spi1_ele1_reg[1]/Q -type DFF DFF
add mapped point spi1/ele1[2]/q spi1_ele1_reg[2]/Q -type DFF DFF
add mapped point spi1/ele1[3]/q spi1_ele1_reg[3]/Q -type DFF DFF
add mapped point spi1/ele1[4]/q spi1_ele1_reg[4]/Q -type DFF DFF
add mapped point spi1/ele1[5]/q spi1_ele1_reg[5]/Q -type DFF DFF
add mapped point spi1/ele1[6]/q spi1_ele1_reg[6]/Q -type DFF DFF
add mapped point spi1/ele1[7]/q spi1_ele1_reg[7]/Q -type DFF DFF
add mapped point spi1/ele1[8]/q spi1_ele1_reg[8]/Q -type DFF DFF
add mapped point spi1/ele1[9]/q spi1_ele1_reg[9]/Q -type DFF DFF
add mapped point spi1/ele1[10]/q spi1_ele1_reg[10]/Q -type DFF DFF
add mapped point spi1/ele1[11]/q spi1_ele1_reg[11]/Q -type DFF DFF
add mapped point spi1/ele1[12]/q spi1_ele1_reg[12]/Q -type DFF DFF
add mapped point spi1/ele1[13]/q spi1_ele1_reg[13]/Q -type DFF DFF
add mapped point spi1/ele1[14]/q spi1_ele1_reg[14]/Q -type DFF DFF
add mapped point spi1/ele1[15]/q spi1_ele1_reg[15]/Q -type DFF DFF
add mapped point spi1/ele1[16]/q spi1_ele1_reg[16]/Q -type DFF DFF
add mapped point spi1/ele1[17]/q spi1_ele1_reg[17]/Q -type DFF DFF
add mapped point spi1/ele1[18]/q spi1_ele1_reg[18]/Q -type DFF DFF
add mapped point spi1/ele1[19]/q spi1_ele1_reg[19]/Q -type DFF DFF
add mapped point spi1/ele1[20]/q spi1_ele1_reg[20]/Q -type DFF DFF
add mapped point spi1/ele1[21]/q spi1_ele1_reg[21]/Q -type DFF DFF
add mapped point spi1/ele1[22]/q spi1_ele1_reg[22]/Q -type DFF DFF
add mapped point spi1/ele1[23]/q spi1_ele1_reg[23]/Q -type DFF DFF
add mapped point spi1/ele1[24]/q spi1_ele1_reg[24]/Q -type DFF DFF
add mapped point spi1/ele1[25]/q spi1_ele1_reg[25]/Q -type DFF DFF
add mapped point spi1/ele1[26]/q spi1_ele1_reg[26]/Q -type DFF DFF
add mapped point spi1/ele1[27]/q spi1_ele1_reg[27]/Q -type DFF DFF
add mapped point spi1/ele1[28]/q spi1_ele1_reg[28]/Q -type DFF DFF
add mapped point spi1/ele1[29]/q spi1_ele1_reg[29]/Q -type DFF DFF
add mapped point spi1/ele1[30]/q spi1_ele1_reg[30]/Q -type DFF DFF
add mapped point spi1/ele1[31]/q spi1_ele1_reg[31]/Q -type DFF DFF
add mapped point spi1/ele2_meta[0]/q spi1_ele2_meta_reg[0]/Q -type DFF DFF
add mapped point spi1/ele2_meta[1]/q spi1_ele2_meta_reg[1]/Q -type DFF DFF
add mapped point spi1/ele2_meta[2]/q spi1_ele2_meta_reg[2]/Q -type DFF DFF
add mapped point spi1/ele2_meta[3]/q spi1_ele2_meta_reg[3]/Q -type DFF DFF
add mapped point spi1/ele2_meta[4]/q spi1_ele2_meta_reg[4]/Q -type DFF DFF
add mapped point spi1/ele2_meta[5]/q spi1_ele2_meta_reg[5]/Q -type DFF DFF
add mapped point spi1/ele2_meta[6]/q spi1_ele2_meta_reg[6]/Q -type DFF DFF
add mapped point spi1/ele2_meta[7]/q spi1_ele2_meta_reg[7]/Q -type DFF DFF
add mapped point spi1/ele2_meta[8]/q spi1_ele2_meta_reg[8]/Q -type DFF DFF
add mapped point spi1/ele2_meta[9]/q spi1_ele2_meta_reg[9]/Q -type DFF DFF
add mapped point spi1/ele2_meta[10]/q spi1_ele2_meta_reg[10]/Q -type DFF DFF
add mapped point spi1/ele2_meta[11]/q spi1_ele2_meta_reg[11]/Q -type DFF DFF
add mapped point spi1/ele2_meta[12]/q spi1_ele2_meta_reg[12]/Q -type DFF DFF
add mapped point spi1/ele2_meta[13]/q spi1_ele2_meta_reg[13]/Q -type DFF DFF
add mapped point spi1/ele2_meta[14]/q spi1_ele2_meta_reg[14]/Q -type DFF DFF
add mapped point spi1/ele2_meta[15]/q spi1_ele2_meta_reg[15]/Q -type DFF DFF
add mapped point spi1/ele2_meta[16]/q spi1_ele2_meta_reg[16]/Q -type DFF DFF
add mapped point spi1/ele2_meta[17]/q spi1_ele2_meta_reg[17]/Q -type DFF DFF
add mapped point spi1/ele2_meta[18]/q spi1_ele2_meta_reg[18]/Q -type DFF DFF
add mapped point spi1/ele2_meta[19]/q spi1_ele2_meta_reg[19]/Q -type DFF DFF
add mapped point spi1/ele2_meta[20]/q spi1_ele2_meta_reg[20]/Q -type DFF DFF
add mapped point spi1/ele2_meta[21]/q spi1_ele2_meta_reg[21]/Q -type DFF DFF
add mapped point spi1/ele2_meta[22]/q spi1_ele2_meta_reg[22]/Q -type DFF DFF
add mapped point spi1/ele2_meta[23]/q spi1_ele2_meta_reg[23]/Q -type DFF DFF
add mapped point spi1/ele2_meta[24]/q spi1_ele2_meta_reg[24]/Q -type DFF DFF
add mapped point spi1/ele2_meta[25]/q spi1_ele2_meta_reg[25]/Q -type DFF DFF
add mapped point spi1/ele2_meta[26]/q spi1_ele2_meta_reg[26]/Q -type DFF DFF
add mapped point spi1/ele2_meta[27]/q spi1_ele2_meta_reg[27]/Q -type DFF DFF
add mapped point spi1/ele2_meta[28]/q spi1_ele2_meta_reg[28]/Q -type DFF DFF
add mapped point spi1/ele2_meta[29]/q spi1_ele2_meta_reg[29]/Q -type DFF DFF
add mapped point spi1/ele2_meta[30]/q spi1_ele2_meta_reg[30]/Q -type DFF DFF
add mapped point spi1/ele2_meta[31]/q spi1_ele2_meta_reg[31]/Q -type DFF DFF
add mapped point spi1/ele2[0]/q spi1_ele2_reg[0]/Q -type DFF DFF
add mapped point spi1/ele2[1]/q spi1_ele2_reg[1]/Q -type DFF DFF
add mapped point spi1/ele2[2]/q spi1_ele2_reg[2]/Q -type DFF DFF
add mapped point spi1/ele2[3]/q spi1_ele2_reg[3]/Q -type DFF DFF
add mapped point spi1/ele2[4]/q spi1_ele2_reg[4]/Q -type DFF DFF
add mapped point spi1/ele2[5]/q spi1_ele2_reg[5]/Q -type DFF DFF
add mapped point spi1/ele2[6]/q spi1_ele2_reg[6]/Q -type DFF DFF
add mapped point spi1/ele2[7]/q spi1_ele2_reg[7]/Q -type DFF DFF
add mapped point spi1/ele2[8]/q spi1_ele2_reg[8]/Q -type DFF DFF
add mapped point spi1/ele2[9]/q spi1_ele2_reg[9]/Q -type DFF DFF
add mapped point spi1/ele2[10]/q spi1_ele2_reg[10]/Q -type DFF DFF
add mapped point spi1/ele2[11]/q spi1_ele2_reg[11]/Q -type DFF DFF
add mapped point spi1/ele2[12]/q spi1_ele2_reg[12]/Q -type DFF DFF
add mapped point spi1/ele2[13]/q spi1_ele2_reg[13]/Q -type DFF DFF
add mapped point spi1/ele2[14]/q spi1_ele2_reg[14]/Q -type DFF DFF
add mapped point spi1/ele2[15]/q spi1_ele2_reg[15]/Q -type DFF DFF
add mapped point spi1/ele2[16]/q spi1_ele2_reg[16]/Q -type DFF DFF
add mapped point spi1/ele2[17]/q spi1_ele2_reg[17]/Q -type DFF DFF
add mapped point spi1/ele2[18]/q spi1_ele2_reg[18]/Q -type DFF DFF
add mapped point spi1/ele2[19]/q spi1_ele2_reg[19]/Q -type DFF DFF
add mapped point spi1/ele2[20]/q spi1_ele2_reg[20]/Q -type DFF DFF
add mapped point spi1/ele2[21]/q spi1_ele2_reg[21]/Q -type DFF DFF
add mapped point spi1/ele2[22]/q spi1_ele2_reg[22]/Q -type DFF DFF
add mapped point spi1/ele2[23]/q spi1_ele2_reg[23]/Q -type DFF DFF
add mapped point spi1/ele2[24]/q spi1_ele2_reg[24]/Q -type DFF DFF
add mapped point spi1/ele2[25]/q spi1_ele2_reg[25]/Q -type DFF DFF
add mapped point spi1/ele2[26]/q spi1_ele2_reg[26]/Q -type DFF DFF
add mapped point spi1/ele2[27]/q spi1_ele2_reg[27]/Q -type DFF DFF
add mapped point spi1/ele2[28]/q spi1_ele2_reg[28]/Q -type DFF DFF
add mapped point spi1/ele2[29]/q spi1_ele2_reg[29]/Q -type DFF DFF
add mapped point spi1/ele2[30]/q spi1_ele2_reg[30]/Q -type DFF DFF
add mapped point spi1/ele2[31]/q spi1_ele2_reg[31]/Q -type DFF DFF
add mapped point spi1/Rx_count[0]/q spi1_Rx_count_reg[0]/Q -type DFF DFF
add mapped point spi1/Rx_count[1]/q spi1_Rx_count_reg[1]/Q -type DFF DFF
add mapped point spi1/Rx_count[2]/q spi1_Rx_count_reg[2]/Q -type DFF DFF
add mapped point spi1/Rx_count[3]/q spi1_Rx_count_reg[3]/Q -type DFF DFF
add mapped point spi1/Rx_count[4]/q spi1_Rx_count_reg[4]/Q -type DFF DFF
add mapped point spi1/Rx_count[5]/q spi1_Rx_count_reg[5]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[0]/q spi1_Rx_data_temp_reg[0]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[1]/q spi1_Rx_data_temp_reg[1]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[2]/q spi1_Rx_data_temp_reg[2]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[3]/q spi1_Rx_data_temp_reg[3]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[4]/q spi1_Rx_data_temp_reg[4]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[5]/q spi1_Rx_data_temp_reg[5]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[6]/q spi1_Rx_data_temp_reg[6]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[7]/q spi1_Rx_data_temp_reg[7]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[8]/q spi1_Rx_data_temp_reg[8]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[9]/q spi1_Rx_data_temp_reg[9]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[10]/q spi1_Rx_data_temp_reg[10]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[11]/q spi1_Rx_data_temp_reg[11]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[12]/q spi1_Rx_data_temp_reg[12]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[13]/q spi1_Rx_data_temp_reg[13]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[14]/q spi1_Rx_data_temp_reg[14]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[15]/q spi1_Rx_data_temp_reg[15]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[16]/q spi1_Rx_data_temp_reg[16]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[17]/q spi1_Rx_data_temp_reg[17]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[18]/q spi1_Rx_data_temp_reg[18]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[19]/q spi1_Rx_data_temp_reg[19]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[20]/q spi1_Rx_data_temp_reg[20]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[21]/q spi1_Rx_data_temp_reg[21]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[22]/q spi1_Rx_data_temp_reg[22]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[23]/q spi1_Rx_data_temp_reg[23]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[24]/q spi1_Rx_data_temp_reg[24]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[25]/q spi1_Rx_data_temp_reg[25]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[26]/q spi1_Rx_data_temp_reg[26]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[27]/q spi1_Rx_data_temp_reg[27]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[28]/q spi1_Rx_data_temp_reg[28]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[29]/q spi1_Rx_data_temp_reg[29]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[30]/q spi1_Rx_data_temp_reg[30]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[31]/q spi1_Rx_data_temp_reg[31]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[32]/q spi1_Rx_data_temp_reg[32]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[33]/q spi1_Rx_data_temp_reg[33]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[34]/q spi1_Rx_data_temp_reg[34]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[35]/q spi1_Rx_data_temp_reg[35]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[36]/q spi1_Rx_data_temp_reg[36]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[37]/q spi1_Rx_data_temp_reg[37]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[38]/q spi1_Rx_data_temp_reg[38]/Q -type DFF DFF
add mapped point spi1/Rx_data_temp[39]/q spi1_Rx_data_temp_reg[39]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[0]/q spi1_conf0_asyn_reg[0]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[1]/q spi1_conf0_asyn_reg[1]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[2]/q spi1_conf0_asyn_reg[2]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[3]/q spi1_conf0_asyn_reg[3]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[4]/q spi1_conf0_asyn_reg[4]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[5]/q spi1_conf0_asyn_reg[5]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[6]/q spi1_conf0_asyn_reg[6]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[7]/q spi1_conf0_asyn_reg[7]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[8]/q spi1_conf0_asyn_reg[8]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[9]/q spi1_conf0_asyn_reg[9]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[10]/q spi1_conf0_asyn_reg[10]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[11]/q spi1_conf0_asyn_reg[11]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[12]/q spi1_conf0_asyn_reg[12]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[13]/q spi1_conf0_asyn_reg[13]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[14]/q spi1_conf0_asyn_reg[14]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[15]/q spi1_conf0_asyn_reg[15]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[16]/q spi1_conf0_asyn_reg[16]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[17]/q spi1_conf0_asyn_reg[17]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[18]/q spi1_conf0_asyn_reg[18]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[19]/q spi1_conf0_asyn_reg[19]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[20]/q spi1_conf0_asyn_reg[20]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[21]/q spi1_conf0_asyn_reg[21]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[22]/q spi1_conf0_asyn_reg[22]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[23]/q spi1_conf0_asyn_reg[23]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[24]/q spi1_conf0_asyn_reg[24]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[25]/q spi1_conf0_asyn_reg[25]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[26]/q spi1_conf0_asyn_reg[26]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[27]/q spi1_conf0_asyn_reg[27]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[28]/q spi1_conf0_asyn_reg[28]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[29]/q spi1_conf0_asyn_reg[29]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[30]/q spi1_conf0_asyn_reg[30]/Q -type DFF DFF
add mapped point spi1/conf0_asyn[31]/q spi1_conf0_asyn_reg[31]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[0]/q spi1_conf1_asyn_reg[0]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[1]/q spi1_conf1_asyn_reg[1]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[2]/q spi1_conf1_asyn_reg[2]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[3]/q spi1_conf1_asyn_reg[3]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[4]/q spi1_conf1_asyn_reg[4]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[5]/q spi1_conf1_asyn_reg[5]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[6]/q spi1_conf1_asyn_reg[6]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[7]/q spi1_conf1_asyn_reg[7]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[8]/q spi1_conf1_asyn_reg[8]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[9]/q spi1_conf1_asyn_reg[9]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[10]/q spi1_conf1_asyn_reg[10]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[11]/q spi1_conf1_asyn_reg[11]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[12]/q spi1_conf1_asyn_reg[12]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[13]/q spi1_conf1_asyn_reg[13]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[14]/q spi1_conf1_asyn_reg[14]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[15]/q spi1_conf1_asyn_reg[15]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[16]/q spi1_conf1_asyn_reg[16]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[17]/q spi1_conf1_asyn_reg[17]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[18]/q spi1_conf1_asyn_reg[18]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[19]/q spi1_conf1_asyn_reg[19]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[20]/q spi1_conf1_asyn_reg[20]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[21]/q spi1_conf1_asyn_reg[21]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[22]/q spi1_conf1_asyn_reg[22]/Q -type DFF DFF
add mapped point spi1/conf1_asyn[23]/q spi1_conf1_asyn_reg[23]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[0]/q spi1_ele1_asyn_reg[0]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[1]/q spi1_ele1_asyn_reg[1]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[2]/q spi1_ele1_asyn_reg[2]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[3]/q spi1_ele1_asyn_reg[3]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[4]/q spi1_ele1_asyn_reg[4]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[5]/q spi1_ele1_asyn_reg[5]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[6]/q spi1_ele1_asyn_reg[6]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[7]/q spi1_ele1_asyn_reg[7]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[8]/q spi1_ele1_asyn_reg[8]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[9]/q spi1_ele1_asyn_reg[9]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[10]/q spi1_ele1_asyn_reg[10]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[11]/q spi1_ele1_asyn_reg[11]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[12]/q spi1_ele1_asyn_reg[12]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[13]/q spi1_ele1_asyn_reg[13]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[14]/q spi1_ele1_asyn_reg[14]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[15]/q spi1_ele1_asyn_reg[15]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[16]/q spi1_ele1_asyn_reg[16]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[17]/q spi1_ele1_asyn_reg[17]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[18]/q spi1_ele1_asyn_reg[18]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[19]/q spi1_ele1_asyn_reg[19]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[20]/q spi1_ele1_asyn_reg[20]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[21]/q spi1_ele1_asyn_reg[21]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[22]/q spi1_ele1_asyn_reg[22]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[23]/q spi1_ele1_asyn_reg[23]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[24]/q spi1_ele1_asyn_reg[24]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[25]/q spi1_ele1_asyn_reg[25]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[26]/q spi1_ele1_asyn_reg[26]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[27]/q spi1_ele1_asyn_reg[27]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[28]/q spi1_ele1_asyn_reg[28]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[29]/q spi1_ele1_asyn_reg[29]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[30]/q spi1_ele1_asyn_reg[30]/Q -type DFF DFF
add mapped point spi1/ele1_asyn[31]/q spi1_ele1_asyn_reg[31]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[0]/q spi1_ele2_asyn_reg[0]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[1]/q spi1_ele2_asyn_reg[1]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[2]/q spi1_ele2_asyn_reg[2]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[3]/q spi1_ele2_asyn_reg[3]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[4]/q spi1_ele2_asyn_reg[4]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[5]/q spi1_ele2_asyn_reg[5]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[6]/q spi1_ele2_asyn_reg[6]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[7]/q spi1_ele2_asyn_reg[7]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[8]/q spi1_ele2_asyn_reg[8]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[9]/q spi1_ele2_asyn_reg[9]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[10]/q spi1_ele2_asyn_reg[10]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[11]/q spi1_ele2_asyn_reg[11]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[12]/q spi1_ele2_asyn_reg[12]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[13]/q spi1_ele2_asyn_reg[13]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[14]/q spi1_ele2_asyn_reg[14]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[15]/q spi1_ele2_asyn_reg[15]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[16]/q spi1_ele2_asyn_reg[16]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[17]/q spi1_ele2_asyn_reg[17]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[18]/q spi1_ele2_asyn_reg[18]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[19]/q spi1_ele2_asyn_reg[19]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[20]/q spi1_ele2_asyn_reg[20]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[21]/q spi1_ele2_asyn_reg[21]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[22]/q spi1_ele2_asyn_reg[22]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[23]/q spi1_ele2_asyn_reg[23]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[24]/q spi1_ele2_asyn_reg[24]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[25]/q spi1_ele2_asyn_reg[25]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[26]/q spi1_ele2_asyn_reg[26]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[27]/q spi1_ele2_asyn_reg[27]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[28]/q spi1_ele2_asyn_reg[28]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[29]/q spi1_ele2_asyn_reg[29]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[30]/q spi1_ele2_asyn_reg[30]/Q -type DFF DFF
add mapped point spi1/ele2_asyn[31]/q spi1_ele2_asyn_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
